### ISSUE TITLE
列举并解释你知道的选择器类型？

### ISSUE THREAD

**Issue by bycgxss** [bycgxss/interview#21]
- 元素选择器
    ```css
    p {
        color: red;
    }
    div {
        color: blue;
    }
    ```
- ID选择器
    ```html
    <p id=”box”>hello world</p>
    <style>
        #box {
            border: 1px solid red;
        }
    </style>
    ```
- 类选择器
    ```html
    <p class=“box active”>饥人谷</p>
    <style>
        .active {
        font-size: 20px;
        }
    </style>
    ```
- 通用选择器
    ```css
    * {
        box-sizing: border-box;
    }
    .box * {
        font-size: 24px;
    }
    ```
- 属性选择器
    - [attr] 选择包含 attr 属性的所有元素，不论 attr 的值为何。
    - [attr=val] 仅选择 attr 属性被赋值为 val 的所有元素。
    - 还有几种不常用的属性选择器
- 组合选择器
    - E, F---多元素选择器，同时匹配所有E元素和F元素，E和F之间用逗号分隔
    - E F---后代元素选择器，匹配所有属于E元素后代的F元素，E和F之间用空格分隔
    - E > F---子元素选择器，匹配所有E元素的子元素F
    - E + F---毗邻元素选择器，匹配所有紧随E元素之后的同级元素F
    - E ~ F---匹配同一父元素下，<E> 元素后的所有 <F> 元素。
